const express=require('express')
const cors=require('cors')
const fileupload=require('express-fileupload')
const AchievmentRoutes=require('./Routes/Achievment.Routes')
const ExperienceRoutes=require('./Routes/Experience.Routes')
const ProjectRoutes=require('./Routes/Project.Routes')
const SkillRoutes=require('./Routes/Skill.Routes')
const UserRoutes=require('./Routes/User.Routes')
const app=express()
app.use(cors())
app.use(express.json())
app.use(fileupload())
app.use('/Achievment',AchievmentRoutes)
app.use('/Experience',ExperienceRoutes)
app.use('/Project',ProjectRoutes)
app.use('/Skill',SkillRoutes)
app.use('/User',UserRoutes)
module.exports = app;
